kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "ibmcloud/arbitrary/secrets/groups/666dd80d-758a-4a32-855d-84a018c58ebf"
type: Opaque
stringData:
  sample-secret: <sample>
